## Frontend image repository
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: portal-frontend
  namespace: flux-system
spec:
  image: ghcr.io/mharikmert/portal-frontend
  interval: 1m0s

---
## Backend image repository

apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: portal-backend
  namespace: flux-system
spec:
  image: ghcr.io/mharikmert/portal-backend
  interval: 1m0s
