apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: home-image-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: home
  policy:
    semver:
      range: 0.x.x
