apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: infra-svg-server-image-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: infra-svg-server
  policy:
    semver:
      range: 0.x.x
