apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: deployments-image-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: deployments
  policy:
    semver:
      range: 0.x.x
